class_info/0/color:
- 0.45323965705321156
- 0.08792637256080282
- 0.9260115510386315
class_info/0/labels:
- 49
- 56
- 78
- 109
- 113
class_info/1/color:
- 0.5294117647058824
- 0.807843137254902
- 0.9215686274509803
class_info/1/labels:
- 2
class_info/10/color:
- 0.791644405373812
- 0.7156875049947278
- 0.3556989472489155
class_info/10/labels:
- 52
- 91
class_info/11/color:
- 0.0
- 1.0
- 1.0
class_info/11/labels:
- 20
- 80
- 83
- 90
- 102
- 116
class_info/12/color:
- 0.7294117647058823
- 0.3333333333333333
- 0.8274509803921568
class_info/12/labels:
- 1
- 25
- 48
- 84
class_info/13/color:
- 0.001049544844725414
- 0.2878140445868147
- 0.6033798786072991
class_info/13/labels:
- 51
- 79
- 86
- 106
- 114
class_info/14/color:
- 0.16047956196106328
- 0.23985421880872038
- 0.977228342645823
class_info/14/labels:
- 136
class_info/15/color:
- 0.0
- 0.0
- 0.0
class_info/15/labels:
- 34
class_info/16/color:
- 0.1561746484296166
- 0.7709084261769606
- 0.7499094987904612
class_info/16/labels:
- 32
class_info/17/color:
- 0.0
- 1.0
- 0.5
class_info/17/labels:
- 76
- 103
class_info/18/color:
- 0.14597064168622553
- 0.19247931363244908
- 0.2579811837322824
class_info/18/labels:
- 43
- 100
- 123
- 144
class_info/19/color:
- 0.8823529411764706
- 0.8823529411764706
- 0.0
class_info/19/labels:
- 16
- 68
class_info/2/color:
- 0.0
- 0.4235294117647059
- 0.0
class_info/2/labels:
- 4
- 72
class_info/20/color:
- 0.18964093624491984
- 0.5298141653772451
- 0.21932483329501207
class_info/20/labels:
- 61
class_info/21/color:
- 0.29411764705882354
- 0.0
- 0.5098039215686274
class_info/21/labels:
- 0
class_info/22/color:
- 0.5019607843137255
- 0.5019607843137255
- 0.5019607843137255
class_info/22/labels:
- 3
- 28
- 101
- 105
class_info/23/color:
- 0.19427991895074004
- 0.5146758569670492
- 0.712759760637419
class_info/23/labels:
- 5
class_info/24/color:
- 0.7026163197928302
- 0.5389206307565594
- 0.0761183308312311
class_info/24/labels:
- 14
- 58
class_info/25/color:
- 0.287910826241623
- 0.6599823003308872
- 0.9899084691624653
class_info/25/labels:
- 53
- 59
- 96
- 121
class_info/26/color:
- 0.5
- 0.5
- 1.0
class_info/26/labels:
- 93
class_info/27/color:
- 1.0
- 0.5
- 0.0
class_info/27/labels:
- 38
- 95
class_info/28/color:
- 0.4452354730837488
- 0.7020357975234616
- 0.08875710034919271
class_info/28/labels:
- 18
- 40
- 42
- 63
- 88
- 95
- 104
- 122
class_info/29/color:
- 1.0
- 0.47058823529411764
- 0.47058823529411764
class_info/29/labels:
- 8
class_info/3/color:
- 0.0
- 0.0
- 0.8823529411764706
class_info/3/labels:
- 21
- 26
- 60
- 128
class_info/30/color:
- 0.8823529411764706
- 0.0
- 0.8823529411764706
class_info/30/labels:
- 15
- 33
- 45
- 64
- 70
- 73
- 77
- 99
class_info/31/color:
- 0.0
- 1.0
- 0.0
class_info/31/labels:
- 17
class_info/32/color:
- 0.7782293245682231
- 0.6157176439757959
- 0.7097569878523822
class_info/32/labels:
- 66
class_info/33/color:
- 0.9590176717336795
- 0.7637557803850368
- 0.5814077162253273
class_info/33/labels:
- 7
- 57
- 117
class_info/34/color:
- 0.002895055330189633
- 0.6340511969209612
- 0.4338463816515534
class_info/34/labels:
- 41
class_info/35/color:
- 0.26891300897295756
- 0.9948411132543332
- 0.18299599117140286
class_info/35/labels:
- 10
- 24
- 35
- 44
- 55
- 62
class_info/36/color:
- 0.7953971227953378
- 0.06975224387572498
- 0.4401345249280487
class_info/36/labels:
- 111
class_info/37/color:
- 0.5
- 0.0
- 0.0
class_info/37/labels:
- 115
class_info/38/color:
- 1.0
- 0.5
- 1.0
class_info/38/labels:
- 112
class_info/39/color:
- 0.8823529411764706
- 0.0
- 0.0
class_info/39/labels:
- 19
- 30
- 31
- 75
- 110
- 23
- 39
- 69
- 97
class_info/4/color:
- 0.5450980392156862
- 0.27058823529411763
- 0.07450980392156863
class_info/4/labels:
- 13
- 94
class_info/40/color:
- 0.3010562959902554
- 0.979707026936908
- 0.8276700908826935
class_info/40/labels:
- 149
class_info/41/color:
- 1.0
- 1.0
- 0.5
class_info/41/labels:
- 22
- 27
- 148
- 149
class_info/42/color:
- 0.45166117208691814
- 0.24192782507592359
- 0.6472813904687642
class_info/42/labels:
- 36
- 82
- 85
- 87
- 134
class_info/43/color:
- 0.5
- 1.0
- 0.0
class_info/43/labels:
- 37
- 47
- 50
- 65
- 71
- 107
- 118
- 124
- 129
- 133
- 145
- 146
class_info/44/color:
- 0.2998201814267084
- 0.8229165491609916
- 0.39155125070638586
class_info/44/labels:
- 138
class_info/45/color:
- 0.4775931712635654
- 0.07985155299277624
- 0.2896548949619272
class_info/45/labels:
- 127
class_info/46/color:
- 0.9570205606588457
- 0.267519074768078
- 0.9914356212822328
class_info/46/labels:
- 98
- 120
class_info/47/color:
- 0.04816014812872993
- 0.7039495834536541
- 0.04781329238306575
class_info/47/labels:
- 81
- 92
- 131
class_info/48/color:
- 0.6031180967281659
- 0.9934980932092142
- 0.4421038786855306
class_info/48/labels:
- 67
- 74
- 89
- 108
- 119
- 130
- 132
- 137
- 141
- 143
- 125
- 135
- 139
- 142
- 147
class_info/49/color:
- 0.7424769624389399
- 0.32603330041591205
- 0.3162571205903788
class_info/49/labels:
- 126
class_info/5/color:
- 0.0
- 0.5
- 1.0
class_info/5/labels:
- 9
- 29
class_info/50/color:
- 0.9850515078572188
- 0.23413937496154313
- 0.641443042091564
class_info/50/labels:
- 12
class_info/6/color:
- 0.573983054300773
- 0.7748737843549258
- 0.617880307538698
class_info/6/labels:
- 46
class_info/7/color:
- 0.8627450980392157
- 0.8627450980392157
- 0.8627450980392157
class_info/7/labels:
- 11
- 52
class_info/8/color:
- 0.9752651606715211
- 0.24629717900547488
- 0.1382271646944223
class_info/8/labels:
- 140
class_info/9/color:
- 0.39215686274509803
- 0.39215686274509803
- 0.39215686274509803
class_info/9/labels:
- 6
- 54
classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
default_color:
- 0.9677975592919913
- 0.44127456009157356
- 0.5358103155058701
